### ISSUE TITLE
eror3

### ISSUE THREAD

**Issue by AliKaramiani** [hampadco/shopSample#4]
PS C:\Users\Click\Desktop\shop\shopSample> dotnet tool uninstall --global dotnet-ef
Tool 'dotnet-ef' (version '8.0.4') was successfully uninstalled.
PS C:\Users\Click\Desktop\shop\shopSample> dotnet tool install --global dotnet-ef
Since you just installed the .NET SDK, you will need to reopen the Command Prompt window before running the tool you installed.
You can invoke the tool using the following command: dotnet-ef
Tool 'dotnet-ef' (version '8.0.4') was successfully installed.
PS C:\Users\Click\Desktop\shop\shopSample> dotnet ef migrations add first
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET program, but dotnet-ef does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
PS C:\Users\Click\Desktop\shop\shopSample>

**Comment by hampadco** [comment]
%USERPROFILE%\.dotnet\tools\dotnet-ef migrations add first
